### ISSUE TITLE
Schema of all componments

### ISSUE THREAD

**Issue by millecentdix** [ADSBexchange/wiki#3]
Hi,
I'm using a custom Pi image on an old Raspberry Pi 2, not very powerfull but it works.
To be a little friendly with it, I want to separate modules on other server, typically in Docker containers.
So, my question is : Is there a schema with differents ports, listener, modes anywhere ?
Thanks !

**Comment by wiedehopf** [comment]
Just run my readsb on the rpi.

Then run a readsb container on the server to get the data, like this for example:
```
  readsb:
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest
    tty: true
    container_name: readsb
    hostname: readsb
    restart: always
    ports:
      - 8080:8080
      - 30005:30005
    environment:
      - READSB_NET_CONNECTOR=192.168.2.33,30005,beast_in
      - TZ=Australia/Perth
      - READSB_NET_ONLY=true
      - READSB_LAT=-33.33333
      - READSB_LON=111.11111
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - READSB_NET_ENABLE=true
    volumes:
      - readsbpb_rrd:/run/collectd
    tmpfs:
      - /run/readsb:size=64M
      - /var/log:size=32M
```
https://sdr-enthusiasts.gitbook.io/ads-b/
